# This file was autogenerated. DO NOT EDIT!
{
  sgr-iosevka-aile = "sha256-Y3GGGRmww4qrtBPuYvRE3FXpoAsqJMc956D1O8wyuco=";
  sgr-iosevka-etoile = "sha256-DqaxGZ4W11mkMO5bNUsVHw7cwEMp+wWoN/+qL+K9izk=";
  sgr-iosevka-term-ss08 = "sha256-UfPp8DCjl/UQT6EMJ67DzSu7FZ63ha+SV8CeseVQz20=";
}
